// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class FloorItResources
{
        public const string leaderboard_drive_distance = "CgkItq30jccQEAIQBQ"; // <GPGSID>
        public const string achievement_nightjar = "CgkItq30jccQEAIQGA"; // <GPGSID>
        public const string achievement_move_on_up = "CgkItq30jccQEAIQDw"; // <GPGSID>
        public const string achievement_double = "CgkItq30jccQEAIQCg"; // <GPGSID>
        public const string leaderboard_bowl_score = "CgkItq30jccQEAIQAg"; // <GPGSID>
        public const string achievement_untraveled = "CgkItq30jccQEAIQFA"; // <GPGSID>
        public const string achievement_baal = "CgkItq30jccQEAIQGQ"; // <GPGSID>
        public const string achievement_triple_double_no_assist = "CgkItq30jccQEAIQKw"; // <GPGSID>
        public const string achievement_hollyhock = "CgkItq30jccQEAIQFw"; // <GPGSID>
        public const string achievement_friendly_fire = "CgkItq30jccQEAIQLQ"; // <GPGSID>
        public const string achievement_wanderer = "CgkItq30jccQEAIQEA"; // <GPGSID>
        public const string leaderboard_floor_it_score = "CgkItq30jccQEAIQAQ"; // <GPGSID>
        public const string achievement_joey = "CgkItq30jccQEAIQFQ"; // <GPGSID>
        public const string achievement_cars_never_die = "CgkItq30jccQEAIQIw"; // <GPGSID>
        public const string achievement_build_a_road = "CgkItq30jccQEAIQBw"; // <GPGSID>
        public const string achievement_wildflower = "CgkItq30jccQEAIQFg"; // <GPGSID>
        public const string achievement_floor_it = "CgkItq30jccQEAIQBg"; // <GPGSID>
        public const string achievement_all_for_myself = "CgkItq30jccQEAIQHg"; // <GPGSID>
        public const string achievement_self_control = "CgkItq30jccQEAIQDA"; // <GPGSID>
        public const string achievement_hit_the_road = "CgkItq30jccQEAIQCA"; // <GPGSID>
        public const string achievement_juggling_master = "CgkItq30jccQEAIQEQ"; // <GPGSID>
        public const string achievement_endless_highway = "CgkItq30jccQEAIQDg"; // <GPGSID>
        public const string achievement_so_thats_what_happens = "CgkItq30jccQEAIQLg"; // <GPGSID>
        public const string achievement_lets_go_away = "CgkItq30jccQEAIQEw"; // <GPGSID>
        public const string achievement_quiet_horses = "CgkItq30jccQEAIQJg"; // <GPGSID>
        public const string achievement_x = "CgkItq30jccQEAIQKQ"; // <GPGSID>
        public const string achievement_by_the_kith_and_the_kin = "CgkItq30jccQEAIQLA"; // <GPGSID>
        public const string achievement_jim_j_bullock = "CgkItq30jccQEAIQCQ"; // <GPGSID>
        public const string achievement_im_not_done = "CgkItq30jccQEAIQIQ"; // <GPGSID>
        public const string achievement_every_super_hero_needs_their_theme_music = "CgkItq30jccQEAIQKA"; // <GPGSID>
        public const string achievement_master_of_none = "CgkItq30jccQEAIQHA"; // <GPGSID>
        public const string achievement_road_blocks = "CgkItq30jccQEAIQHw"; // <GPGSID>
        public const string achievement_thats_not_me = "CgkItq30jccQEAIQJw"; // <GPGSID>
        public const string achievement_the_road = "CgkItq30jccQEAIQDQ"; // <GPGSID>
        public const string achievement_highwayman = "CgkItq30jccQEAIQIA"; // <GPGSID>
        public const string leaderboard_drive_score = "CgkItq30jccQEAIQAw"; // <GPGSID>
        public const string achievement_conic = "CgkItq30jccQEAIQGw"; // <GPGSID>
        public const string achievement_chelseas_law = "CgkItq30jccQEAIQKg"; // <GPGSID>
        public const string achievement_who_will_fall_far_behind = "CgkItq30jccQEAIQJA"; // <GPGSID>
        public const string achievement_the_elements = "CgkItq30jccQEAIQIg"; // <GPGSID>
        public const string achievement_dont_stop = "CgkItq30jccQEAIQEg"; // <GPGSID>
        public const string achievement_lump_sum = "CgkItq30jccQEAIQHQ"; // <GPGSID>
        public const string achievement_turkey = "CgkItq30jccQEAIQCw"; // <GPGSID>
        public const string achievement_if_i_had_a_heart = "CgkItq30jccQEAIQJQ"; // <GPGSID>
        public const string leaderboard_floor_it_distance = "CgkItq30jccQEAIQBA"; // <GPGSID>
        public const string achievement______ = "CgkItq30jccQEAIQGg"; // <GPGSID>

}

