// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class FloorItResources
{
        public const string achievement_get_100_points_in_the_floor_it_game_type = "CgkItq30jccQEAIQBg"; // <GPGSID>
        public const string achievement_get_500_points_in_the_floor_it_game_type = "CgkItq30jccQEAIQBw"; // <GPGSID>
        public const string achievement_get_100_points_in_the_bowl_game_type = "CgkItq30jccQEAIQCQ"; // <GPGSID>
        public const string achievement_get_500_points_in_the_bowl_game_type = "CgkItq30jccQEAIQCg"; // <GPGSID>
        public const string achievement_get_100_points_in_the_drive_game_type = "CgkItq30jccQEAIQDA"; // <GPGSID>
        public const string achievement_get_1000_points_in_the_drive_game_type = "CgkItq30jccQEAIQDg"; // <GPGSID>
        public const string leaderboard_drive_farthest_distance = "CgkItq30jccQEAIQBQ"; // <GPGSID>
        public const string achievement_get_500_points_in_the_drive_game_type = "CgkItq30jccQEAIQDQ"; // <GPGSID>
        public const string achievement_get_1000_points_in_the_floor_it_game_type = "CgkItq30jccQEAIQCA"; // <GPGSID>
        public const string leaderboard_drive_highscore = "CgkItq30jccQEAIQAw"; // <GPGSID>
        public const string leaderboard_floor_it_highscore = "CgkItq30jccQEAIQAQ"; // <GPGSID>
        public const string achievement_get_1000_points_in_the_bowl_game_type = "CgkItq30jccQEAIQCw"; // <GPGSID>
        public const string leaderboard_bowl_highscore = "CgkItq30jccQEAIQAg"; // <GPGSID>
        public const string leaderboard_floor_it_farthest_distance = "CgkItq30jccQEAIQBA"; // <GPGSID>

}

